-- V43 + Seed Data for cn_product_catalog
-- Run this in Supabase SQL Editor after migration V43

-- 1. Create table (idempotent)
CREATE TABLE IF NOT EXISTS cn_product_catalog (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hs_code         VARCHAR(20) NOT NULL,
    category        VARCHAR(100) NOT NULL,
    subcategory     VARCHAR(100),
    product_name    TEXT NOT NULL,
    product_type    VARCHAR(100),
    specs           JSONB DEFAULT '{}',
    price_min_usd   NUMERIC,
    price_max_usd   NUMERIC,
    price_avg_usd   NUMERIC,
    moq_min         INTEGER,
    variants        TEXT[] DEFAULT '{}',
    source_url      TEXT,
    marketplace     VARCHAR(50) DEFAULT 'Alibaba',
    confidence      NUMERIC DEFAULT 0.5,
    notes           TEXT,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cn_catalog_hs ON cn_product_catalog(hs_code);
CREATE INDEX IF NOT EXISTS idx_cn_catalog_category ON cn_product_catalog(category);
GRANT SELECT, INSERT, UPDATE ON cn_product_catalog TO anon, authenticated, service_role;

-- 2. Seed data: 6 electronics categories
INSERT INTO cn_product_catalog (hs_code, category, subcategory, product_name, product_type, specs, price_min_usd, price_max_usd, price_avg_usd, moq_min, variants, source_url, marketplace, confidence, notes)
VALUES
-- ========== LED LAMPS (HS 8539) ==========
('85395200', 'Lighting', 'LED Bulbs', 'LED A19 Bulb 9W 800lm', 'LED Lamp', '{"wattage": "9W", "lumens": "800", "color_temp": "3000-6500K", "base": "E27", "voltage": "AC 85-265V", "lifespan": "25000h", "cri": ">80"}', 0.30, 0.80, 0.55, 100, ARRAY['E27', 'B22', 'GU10'], 'https://www.alibaba.com/showroom/led-lamp.html', 'Alibaba', 0.6, 'FOB Shenzhen. Basic LED bulb, no dimming.'),
('85395200', 'Lighting', 'LED Desk Lamps', 'USB Rechargeable LED Desk Lamp', 'LED Lamp', '{"wattage": "5-12W", "lumens": "400-800", "battery": "1800-2400mAh", "color_temp": "3000-6500K", "charging": "USB-C", "features": "dimmable, touch control"}', 3.50, 8.50, 5.80, 50, ARRAY['With USB charging', 'Battery only', 'With wireless charger'], 'https://www.alibaba.com/countrysearch/CN/led-desk-lamp-price.html', 'Alibaba', 0.6, 'FOB Shenzhen/Zhongshan. Eye-care design, adjustable brightness.'),
('85395000', 'Lighting', 'LED Floodlights', 'LED Floodlight 50W 100W Outdoor IP65', 'LED Lamp', '{"wattage": "50-200W", "lumens": "5000-20000", "beam_angle": "120°", "ip_rating": "IP65", "material": "Aluminum + PC", "lifespan": "50000h"}', 5.00, 25.00, 12.00, 50, ARRAY['50W', '100W', '150W', '200W'], 'https://www.alibaba.com/showroom/led-lamp.html', 'Alibaba', 0.6, 'FOB Zhongshan. Suitable for stadiums, parking lots, gardens.'),
('85395100', 'Lighting', 'LED Panels', 'LED Panel Light 600x600mm 48W', 'LED Lamp', '{"wattage": "24-72W", "size": "600x600mm", "lumens": "2400-7200", "color_temp": "3000-6500K", "ip_rating": "IP20", "installation": "recessed/surface"}', 6.00, 18.00, 11.00, 50, ARRAY['24W 300x300', '36W 300x600', '48W 600x600', '72W 600x1200'], 'https://www.alibaba.com/showroom/led-lamp.html', 'Alibaba', 0.6, 'FOB Shenzhen. Office/commercial lighting.'),
('85395200', 'Lighting', 'LED Strip Lights', 'RGB LED Strip Light 5M 5050 SMD', 'LED Lamp', '{"led_type": "5050 SMD", "length": "5M", "voltage": "DC 12V", "color": "RGB + W", "waterproof": "IP20/IP65", "control": "IR remote + app"}', 2.00, 8.00, 4.50, 50, ARRAY['RGB 5M', 'RGBW 5M', 'RGBIC 5M', 'Single color 5M'], 'https://www.alibaba.com/showroom/led-lamp.html', 'Alibaba', 0.6, 'FOB Shenzhen. Smart phone app control option.'),

-- ========== POWER BANKS (HS 8507) ==========
('85076000', 'Electronics', 'Power Banks', '10000mAh Power Bank PD 22.5W Fast Charging', 'Power Bank', '{"capacity": "10000mAh", "output": "22.5W PD", "input": "USB-C 18W", "cells": "Li-polymer", "features": "digital display, dual USB-A + USB-C", "size": "147x71x15mm", "weight": "200g"}', 5.50, 8.50, 6.80, 10, ARRAY['10000mAh standard', '10000mAh magnetic', '10000mAh with cable', '10000mAh light'], 'https://electronics.alibaba.com/buyingguides/china-power-bank-price-guide-what-to-pay-avoid', 'Alibaba', 0.7, 'FOB Shenzhen. CCC certified. $5.49-$6.89 for 10,000mAh 22.5W units per Alibaba buying guide 2026.'),
('85076000', 'Electronics', 'Power Banks', '20000mAh Power Bank PD 45W Fast Charging', 'Power Bank', '{"capacity": "20000mAh", "output": "45W PD", "input": "USB-C 30W", "cells": "Li-polymer", "features": "dual USB-C, LED display, aircraft-safe", "size": "160x80x20mm", "weight": "350g"}', 12.00, 22.00, 16.00, 10, ARRAY['20000mAh 45W', '20000mAh 65W', '20000mAh with AC plug'], 'https://www.alibaba.com/showroom/10000mah-power-banks.html', 'Alibaba', 0.6, 'FOB Shenzhen. Suitable for laptop charging.'),
('85076000', 'Electronics', 'Power Banks', '5000mAh Magnetic Wireless Power Bank', 'Power Bank', '{"capacity": "5000mAh", "wireless": "15W Qi2", "wired": "20W PD", "cells": "Li-polymer", "features": "MagSafe compatible, slim 8mm", "size": "105x68x8mm", "weight": "130g"}', 7.00, 14.00, 9.50, 20, ARRAY['5000mAh white', '5000mAh black', '5000mAh blue', '5000mAh pink'], 'https://www.alibaba.com/showroom/10000mah-power-banks.html', 'Alibaba', 0.6, 'FOB Shenzhen. Ultra-slim magnetic design for iPhone.'),
('85076000', 'Electronics', 'Power Banks', '30000mAh Power Station AC Output', 'Power Bank', '{"capacity": "30000mAh", "ac_output": "110W/220W", "usb_output": "65W PD", "cells": "Li-ion 18650", "features": "AC outlet, DC, USB, LED flashlight", "size": "210x130x50mm", "weight": "800g"}', 25.00, 50.00, 35.00, 10, ARRAY['30000mAh 110W', '30000mAh 220W'], 'https://www.alibaba.com/showroom/10000mah-power-banks.html', 'Alibaba', 0.5, 'FOB Shenzhen. Portable power station for camping/emergency.'),

-- ========== TWS EARPHONES (HS 8518) ==========
('85183000', 'Electronics', 'TWS Earphones', 'Basic TWS Earbuds Bluetooth 5.3', 'TWS Earphone', '{"bluetooth": "5.3", "chip": "JL6983", "driver": "10mm", "battery_earbud": "25mAh", "battery_case": "180mAh", "playtime": "3-5h", "charging": "Type-C", "waterproof": "IPX4"}', 1.80, 3.50, 2.40, 50, ARRAY['White', 'Black', 'Blue', 'Red'], 'https://www.alibaba.com/showroom/tws-headphones.html', 'Alibaba', 0.6, 'FOB Shenzhen. Basic TWS with 180mAh charging case. MOQ 50-1000pcs.'),
('85183000', 'Electronics', 'TWS Earphones', 'ANC TWS Earbuds Hybrid Noise Cancelling 45dB', 'TWS Earphone', '{"bluetooth": "5.3", "chip": "ATS3015", "anc": "Hybrid ANC -45dB", "driver": "13mm", "battery_earbud": "45mAh", "battery_case": "500mAh", "playtime": "6-8h", "charging": "Type-C + wireless", "waterproof": "IPX5"}', 8.00, 20.00, 12.99, 10, ARRAY['White', 'Black'], 'https://www.alibaba.com/showroom/tws-headphones.html', 'Alibaba', 0.6, 'FOB Shenzhen. 6 mic hybrid ANC, support APP, wireless charging.'),
('85183000', 'Electronics', 'TWS Earphones', 'TWS Earbuds with Digital Display LED', 'TWS Earphone', '{"bluetooth": "5.3", "chip": "JL6983", "driver": "13mm", "battery_earbud": "35mAh", "battery_case": "300mAh", "display": "LED battery %", "playtime": "4-6h", "charging": "Type-C"}', 2.50, 5.50, 3.80, 20, ARRAY['i12 style', 'i12 Pro style', 'A6s style', 'T20 style'], 'https://romantech.en.made-in-china.com/product/bFRfsPSMMvty/China-Wholesale-Bluetooth-Wireless-Tws-Earbuds-Earphone-in-Multiple-Colors-for-Bulk-Orders.html', 'Alibaba', 0.6, 'FOB Shenzhen. LED display on case showing battery level. Popular models.'),
('85183000', 'Electronics', 'TWS Earphones', 'Open-Ear TWS Earbuds Air Conduction', 'TWS Earphone', '{"bluetooth": "5.3", "driver": "16mm", "type": "open-ear/air conduction", "battery": "60mAh earbud", "playtime": "8h", "charging": "Type-C"}', 6.00, 15.00, 9.50, 20, ARRAY['Black', 'White', 'Beige', 'Grey'], 'https://www.alibaba.com/showroom/tws-headphones.html', 'Alibaba', 0.6, 'FOB Shenzhen. Open-ear design for sports/situational awareness.'),

-- ========== PHONE CABLES (HS 8544) ==========
('85444200', 'Electronics', 'Phone Cables', 'USB-C to USB-C Cable PD 60W 1M Nylon Braided', 'Data Cable', '{"connector": "USB-C to USB-C", "power": "60W PD 3.0", "data": "USB 2.0 480Mbps", "length": "1M", "material": "nylon braided", "features": "5A e-marker chip"}', 0.55, 1.50, 0.85, 20, ARRAY['0.5M', '1M', '2M', '3M'], 'https://www.alibaba.com/pla/240W-USB-C-Type-C-2_1601690168045.html', 'Alibaba', 0.6, 'FOB Shenzhen. Bulk pricing at 100+ units. $0.55-1.49.'),
('85444200', 'Electronics', 'Phone Cables', 'USB-A to USB-C Fast Charging Cable 3A', 'Data Cable', '{"connector": "USB-A to USB-C", "power": "3A/18W", "data": "USB 2.0", "length": "1M", "material": "TPE/braided"}', 0.30, 0.80, 0.50, 100, ARRAY['0.5M', '1M', '2M', '3M'], 'https://www.alibaba.com/showroom/usb-type-c-flat-cable.html', 'Alibaba', 0.6, 'FOB Shenzhen. Standard USB-A to C cable. MOQ 100-1000.'),
('85444200', 'Electronics', 'Phone Cables', '3-in-1 Retractable Charging Cable', 'Data Cable', '{"connectors": "Lightning + USB-C + Micro USB", "power": "3A", "length": "1.2M", "type": "retractable", "material": "ABS + TPE"}', 1.30, 2.50, 1.80, 20, ARRAY['Black', 'White', 'Red', 'Blue'], 'https://www.alibaba.com/showroom/wholesale-cable-usb-1m.html', 'Alibaba', 0.6, 'FOB Shenzhen. 3-in-1 retractable design. MOQ 20-100.'),
('85444200', 'Electronics', 'Phone Cables', 'USB-C Cable 240W 5A Fast Charging', 'Data Cable', '{"connector": "USB-C to USB-C", "power": "240W 5A", "data": "USB 3.2 Gen2 10Gbps", "length": "1.5M", "material": "nylon braided + aluminum shell", "features": "e-marker, 4K video"}', 1.95, 3.50, 2.49, 10, ARRAY['1M', '1.5M', '2M'], 'https://www.alibaba.com/pla/240W-USB-C-Type-C-2_1601690168045.html', 'Alibaba', 0.6, 'FOB Shenzhen. 240W PD 3.1, suitable for laptop charging. MOQ 5-20.'),

-- ========== SMART WATCHES (HS 8517) ==========
('85176200', 'Electronics', 'Smart Watches', 'Basic Fitness Tracker Smart Band', 'Smart Watch', '{"display": "0.96-1.3 inch TFT color", "features": "heart rate, SpO2, step counter, sleep monitor", "battery": "200mAh, 7-10 days", "waterproof": "IP67", "compatibility": "iOS/Android"}', 2.88, 5.00, 3.50, 10, ARRAY['Black', 'Blue', 'Purple', 'Orange'], 'https://www.alibaba.com/showroom/smartwatch-price.html', 'Alibaba', 0.6, 'FOB Shenzhen. Screenless or small TFT display. Basic health tracking.'),
('85176200', 'Electronics', 'Smart Watches', 'Fitness Smart Watch 1.96 inch TFT BT Call', 'Smart Watch', '{"display": "1.96 inch TFT", "features": "BT call, heart rate, SpO2, sleep, 100+ sports", "battery": "300mAh, 7-14 days", "waterproof": "IP68/3ATM", "compatibility": "iOS/Android"}', 6.90, 12.00, 8.50, 2, ARRAY['Black', 'Silver', 'Pink', 'Green'], 'https://www.alibaba.com/showroom/smartwatch-price.html', 'Alibaba', 0.7, 'FOB Shenzhen. Rugged/sport design. Popular KT71 style. MOQ 1-10.'),
('85176200', 'Electronics', 'Smart Watches', 'Premium AMOLED Smart Watch ECG Bluetooth Call', 'Smart Watch', '{"display": "1.43 inch AMOLED 466x466", "features": "ECG, blood pressure, BT call, GPS, AI voice", "battery": "400mAh, 14 days", "waterproof": "5ATM", "sensors": "heart rate, SpO2, accelerometer, gyroscope"}', 15.00, 37.00, 25.00, 10, ARRAY['Silver + Leather', 'Black + Silicone', 'Gold + Milanese'], 'https://www.alibaba.com/showroom/smartwatch-price.html', 'Alibaba', 0.6, 'FOB Shenzhen. Round luxury design, ECG + health monitoring.'),
('85176200', 'Electronics', 'Smart Watches', 'Smart Watch for Kids GPS Tracker', 'Smart Watch', '{"display": "1.4 inch TFT", "features": "GPS+LBS+WiFi tracking, SOS, 2G/4G, camera", "battery": "600mAh", "compatibility": "iOS/Android with app"}', 8.00, 20.00, 13.00, 10, ARRAY['Blue', 'Pink', 'Green'], 'https://www.alibaba.com/showroom/smartwatch-price.html', 'Alibaba', 0.5, 'FOB Shenzhen. Child safety smart watch with GPS tracker.'),

-- ========== BLUETOOTH SPEAKERS (HS 8518) ==========
('85182200', 'Electronics', 'Bluetooth Speakers', 'Mini Bluetooth Speaker Portable 5W', 'Bluetooth Speaker', '{"power": "5W", "bluetooth": "5.0", "battery": "500mAh", "playtime": "4-6h", "charging": "Type-C", "features": "TF card, FM radio, TWS pairing"}', 2.63, 5.50, 3.68, 50, ARRAY['Black', 'White', 'Blue', 'Red', 'Green'], 'https://www.alibaba.com/showroom/wholesale-bluetooth-speakers.html', 'Alibaba', 0.6, 'FOB Shenzhen. Mini speaker with FM radio. MOQ 50-100.'),
('85182200', 'Electronics', 'Bluetooth Speakers', 'IPX7 Waterproof Bluetooth Speaker', 'Bluetooth Speaker', '{"power": "10W", "bluetooth": "5.3", "battery": "1800mAh", "playtime": "10-12h", "waterproof": "IPX7", "features": "suction cup/magnetic mount, speakerphone, TWS"}', 3.69, 6.50, 4.29, 100, ARRAY['Black', 'Blue', 'Orange', 'Camo'], 'https://www.alibaba.com/product-detail/Most-Selling-Product-In-Alibaba-Mini_1601010445951.html', 'Alibaba', 0.6, 'FOB Shenzhen. Shower/outdoor speaker with suction cup. MOQ 100.'),
('85182200', 'Electronics', 'Bluetooth Speakers', 'Portable Bluetooth Speaker 20W Stereo', 'Bluetooth Speaker', '{"power": "20W (2x10W stereo)", "bluetooth": "5.3", "battery": "3600mAh", "playtime": "8-12h", "waterproof": "IPX6", "features": "RGB lights, bass radiator, TWS, EQ modes"}', 4.90, 9.86, 6.50, 50, ARRAY['Black', 'Black + RGB', 'Camo + RGB'], 'https://www.alibaba.com/showroom/wholesale-bluetooth-speakers.html', 'Alibaba', 0.6, 'FOB Shenzhen. RGB LED lighting, portable with handle/rope. MOQ 50-100.'),
('85182200', 'Electronics', 'Bluetooth Speakers', 'Smart Speaker with Wireless Charger + Alarm', 'Bluetooth Speaker', '{"power": "15W speaker + 15W wireless charger", "bluetooth": "5.0", "features": "QI wireless charging, alarm clock, night light, USB port", "battery": "2400mAh"}', 8.00, 16.00, 11.00, 20, ARRAY['White', 'Black', 'Wood grain'], 'https://www.alibaba.com/product-detail/New-Bluetooth-Speaker-Multifunctional-Wireless-Charger_1601198917713.html', 'Alibaba', 0.5, 'FOB Shenzhen. 3-in-1: speaker + charger + alarm clock. MOQ 20.');
