-- V54: Complete certification requirements (all HS chapters)
-- Source: UzStandard Agency, Delta Global Solutions, USDA FAIRS

INSERT INTO certification_requirements (hs_chapter, hs_description, cert_type, cert_name_uz, cert_name_en, is_mandatory, estimated_cost_usd, validity_days, testing_days, notes)
VALUES
    ('01', 'Tirik hayvonlar', 'SanEpid', 'Veterinariya sertifikati', 'Veterinary Certificate', true, 500, 180, 21, 'Import permits required. Quarantine period may apply.'),
    ('03', 'Baliq va dengiz mahsulotlari', 'SanEpid', 'Veterinariya sertifikati', 'Veterinary Certificate', true, 400, 180, 21, 'Sanitary certificate also required.'),
    ('04', 'Sut mahsulotlari', 'SanEpid', 'Veterinariya sertifikati', 'Veterinary Certificate', true, 500, 180, 21, 'Heat treatment certification required.'),
    ('05', 'Hayvonot mahsulotlari', 'SanEpid', 'Sanitariya-epidemiologik xulosa', 'Sanitary-Epidemiological Certificate', true, 400, 365, 14, 'Standard animal product certification.'),
    ('06', 'Tirik o''simliklar', 'SanEpid', 'Fitosanitar sertifikat', 'Phytosanitary Certificate', true, 250, 180, 14, 'Plant quarantine certificate required.'),
    ('09', 'Qahva, choy, ziravorlar', 'SanEpid', 'Sanitariya-epidemiologik xulosa', 'Sanitary-Epidemiological Certificate', true, 350, 365, 14, 'Pesticide residue testing required.'),
    ('11', 'Un va don mahsulotlari', 'SanEpid', 'Sanitariya-epidemiologik xulosa', 'Sanitary-Epidemiological Certificate', true, 300, 365, 14, 'GMO testing required for wheat flour.'),
    ('12', 'Yog''li urug''lar', 'SanEpid', 'Fitosanitar sertifikat', 'Phytosanitary Certificate', true, 250, 365, 14, 'Seed certification for agricultural use.'),
    ('13', 'Shelfak va smolalar', 'CoC', 'Muvofiqlik sertifikati', 'Certificate of Conformity', true, 300, 365, 14, 'Standard chemical certification.'),
    ('14', 'O''simlik materiallari', 'SanEpid', 'Fitosanitar sertifikat', 'Phytosanitary Certificate', true, 250, 180, 14, 'Plant origin certification.'),
    ('16', 'Go''sht va baliq mahsulotlari', 'SanEpid', 'Sanitariya-epidemiologik xulosa', 'Sanitary-Epidemiological Certificate', true, 500, 180, 21, 'Canned goods require additional testing.'),
    ('18', 'Kakao mahsulotlari', 'SanEpid', 'Sanitariya-epidemiologik xulosa', 'Sanitary-Epidemiological Certificate', true, 350, 365, 14, 'Standard food certification.'),
    ('19', 'Don mahsulotlari', 'SanEpid', 'Sanitariya-epidemiologik xulosa', 'Sanitary-Epidemiological Certificate', true, 300, 365, 14, 'Bread, pasta, cookies.'),
    ('20', 'Sabzavot va meva konservalari', 'SanEpid', 'Sanitariya-epidemiologik xulosa', 'Sanitary-Epidemiological Certificate', true, 350, 365, 14, 'Preserved food certification.'),
    ('21', 'Turli oziq-ovqatlar', 'SanEpid', 'Sanitariya-epidemiologik xulosa', 'Sanitary-Epidemiological Certificate', true, 350, 365, 14, 'Sauces, spices, additives.'),
    ('23', 'Ozuqa va yem', 'SanEpid', 'Sanitariya-epidemiologik xulosa', 'Sanitary-Epidemiological Certificate', true, 350, 365, 14, 'Feed certification for animal consumption.'),
    ('26', 'Rudalar', 'CoC', 'Muvofiqlik sertifikati', 'Certificate of Conformity', true, 800, 365, 30, 'Mining products. Radiation testing required.'),
    ('35', 'Albumin va fermentlar', 'CoC', 'Muvofiqlik sertifikati', 'Certificate of Conformity', true, 400, 365, 14, 'Chemical certification for industrial enzymes.'),
    ('36', 'Porox va portlovchilar', 'CoC', 'Maxsus ruxsatnoma', 'Special Permit', true, 2000, 365, 60, 'Ministry of Internal Affairs special permit required.'),
    ('37', 'Foto mahsulotlar', 'CoC', 'Muvofiqlik sertifikati', 'Certificate of Conformity', false, 200, 365, 7, 'Voluntary certification.'),
    ('41', 'Teri va xom teri', 'CoC', 'Muvofiqlik sertifikati', 'Certificate of Conformity', true, 300, 365, 14, 'Leather certification.'),
    ('42', 'Teri buyumlari', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 200, 365, 7, 'Voluntary for leather goods.'),
    ('43', 'Mo''yna', 'CoC', 'Muvofiqlik sertifikati', 'Certificate of Conformity', true, 400, 365, 14, 'Fur products certification.'),
    ('45', 'Po''kak mahsulotlari', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 150, 365, 7, 'Voluntary certification.'),
    ('46', 'Somon va to''qima', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 150, 365, 7, 'Voluntary for straw products.'),
    ('47', 'Qog''oz massasi', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 200, 365, 7, 'Voluntary.'),
    ('49', 'Kitob va bosma', null, 'Talab qilinmaydi', 'Not Required', false, 0, 0, 0, 'No certification required for printed materials.'),
    ('50', 'Ipak', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 200, 365, 7, 'Voluntary.'),
    ('51', 'Jun', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 200, 365, 7, 'Voluntary.'),
    ('53', 'O''simlik tolalari', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 200, 365, 7, 'Voluntary.'),
    ('56', 'Vatka va namat', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 200, 365, 7, 'Voluntary.'),
    ('57', 'Gilamlar', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 200, 365, 7, 'Voluntary for carpets.'),
    ('58', 'Maxsus matolar', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 200, 365, 7, 'Voluntary.'),
    ('59', 'Emdirilgan matolar', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 200, 365, 7, 'Voluntary.'),
    ('64', 'Oyoq kiyimlari', 'CoC', 'Muvofiqlik sertifikati', 'Certificate of Conformity', true, 300, 365, 14, 'Children''s footwear has stricter requirements.'),
    ('65', 'Bosh kiyimlari', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 200, 365, 7, 'Voluntary for headgear.'),
    ('66', 'Soyabonlar', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 150, 365, 7, 'Voluntary.'),
    ('67', 'Tayyor pat va tuklar', 'SanEpid', 'Sanitariya-epidemiologik xulosa', 'Sanitary-Epidemiological Certificate', true, 300, 365, 14, 'Disinfection certificate required.'),
    ('68', 'Tosh va gips', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 200, 365, 7, 'Voluntary for construction materials.'),
    ('71', 'Qimmatbaho metallar', 'CoC', 'Maxsus ruxsatnoma', 'Special Permit', true, 1000, 365, 30, 'State assay office inspection required.'),
    ('75', 'Nikel', 'CoC', 'Muvofiqlik sertifikati', 'Certificate of Conformity', true, 350, 365, 14, 'Standard metal certification.'),
    ('78', 'Qo''rg''oshin', 'CoC', 'Muvofiqlik sertifikati', 'Certificate of Conformity', true, 350, 365, 14, 'Environmental permit may be required.'),
    ('79', 'Rux', 'CoC', 'Muvofiqlik sertifikati', 'Certificate of Conformity', true, 350, 365, 14, 'Standard metal certification.'),
    ('80', 'Qalay', 'CoC', 'Muvofiqlik sertifikati', 'Certificate of Conformity', true, 350, 365, 14, 'Standard metal certification.'),
    ('81', 'Boshqa metallar', 'CoC', 'Muvofiqlik sertifikati', 'Certificate of Conformity', true, 350, 365, 14, 'Standard metal certification.'),
    ('82', 'Asboblar', 'CoC', 'Muvofiqlik sertifikati', 'Certificate of Conformity', true, 300, 365, 14, 'Power tools require additional safety testing.'),
    ('83', 'Turli metall buyumlar', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 200, 365, 7, 'Locks, fittings, etc.'),
    ('89', 'Kemalar', 'CoC', 'Maxsus texnik sertifikat', 'Technical Certificate', true, 2000, 365, 45, 'Maritime vessel certification.'),
    ('91', 'Soatlar', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 150, 365, 7, 'Voluntary.'),
    ('92', 'Musiqa asboblari', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 150, 365, 7, 'Voluntary.'),
    ('93', 'Qurol', 'CoC', 'Maxsus ruxsatnoma', 'Special Permit', true, 3000, 365, 90, 'Ministry of Internal Affairs special permit.'),
    ('96', 'Turli mahsulotlar', 'CoC', 'Ixtiyoriy sertifikat', 'Voluntary Certificate', false, 150, 365, 7, 'Miscellaneous products.'),
    ('97', 'San''at asarlari', null, 'Talab qilinmaydi', 'Not Required', false, 0, 0, 0, 'Special customs procedure for artworks.')
ON CONFLICT DO NOTHING;
